[project]
name = "fashnai"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
  "fastapi",
  "uvicorn",
  "python-multipart",
  "python-dotenv",
  "pydantic",
  "aiohttp",
  "aiofiles",
  "beautifulsoup4",
  "google-genai",
  "google-search-results",
  "duckduckgo-search",
  "pandas",
  "pillow",
  "scikit-learn",
  "sqlalchemy",
  "agno",
  "azure-ai-inference",
  "crawl4ai",
  "google-adk"
]

[tool.vercel]
entrypoint = "backend.api:app"